### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [DenisBencic/Slovenske-fakultete-PB1-#1]
@DenisBencic, svetujem, da repozitorij preimenuješ npr. na `Slovenske-fakultete` - v vsakem primeru ni potrebe, da se v imenu pojavijo trije zaporedni pomišljaji.

Mimogrede, @hanaKel, izberi **Watch** na repozitoriju, da boš dobivala obvestila (tudi, če nisi eksplicitno označena, tako kot tukaj).

**Comment by DenisBencic** [comment]
Hvala za opozorilo. Popravil sem odvečne pomišljaje in samo ime repozitorija.

**Comment by jaanos** [comment]
Še vedno imata na koncu imena en odvečen pomišljaj.

Ko razrešita težavo, opisano v zadevi, jo lahko zapreta s klikom na *Close issue* (ali *Close with comment*, če ob tem še kaj napišeta).
