### ISSUE TITLE
Program in predloge

### ISSUE THREAD

**Issue by jaanos** [DenisBencic/Slovenske-fakultete-PB1-#2]
Trenutno imata v programu `SlovenskeFakultete.py` skupaj uvoz in spletni vmesnik - svetujem, da to ločita in poskrbita, da se uvoz izvede ob zagonu spletnega vmesnika le, če baza še ne obstaja. Svetujem tudi, da ločita podatke od programov - za podatke je seveda smiselno, da so v mapi `data`, medtem ko naj bo vsaj glavni program v vrhnji mapi repozitorija (ostali so lahko zraven, ali pa v svoji mapi kot modul - npr. če jih imata v mapi `koda`, potem naj bo v tej mapi tudi prazna datoteka `__init__.py`, v glavnem programu pa npr. `uvoz.py` vključita z `import koda.uvoz` oziroma z nečim ekvivalentnim).

Nadalje vidim, da trenutno vračata HTML kar neposredno iz posameznih funkcij - to bo zelo nepregledno, tako da svetujem, da namesto tega uporabljata predloge, ki jih postavita v mapo `views` in kličeta s `template` (poglejta si, kako je to narejeno v [vzorčnem projektu](https://github.com/jaanos/podatkovne-baze-1/tree/main/projekt)).

Nazadnje opažam še tole:
https://github.com/DenisBencic/Slovenske-fakultete-PB1-/blob/16074976056d4c991e4b93d579c69ee9fb3e4f96/data/SlovenskeFakultete.py#L83-L86
Če želita klicati te funkcije, seveda dodajta še oklepaje (npr. `povezava.commit()`). Naj pa opomnim, da se v trenutni obliki te funkcije ne bi nikoli izvedle, saj pred tem z `run` zaženeta spletni strežnik, ta se pa nikoli ne konča (če ga prekineta, se konča program). Uporaba `povezava.commit()` je seveda smiselna po vsakem "enotskem" spreminjanju baze (še bolje pa bo, če ustrezne spremembe naredita znotraj bloka `with povezava:`). Kar se kurzorjev tiče, bo najbolje, če vsak klic metode v modelu (tj., vsaka interakcija z bazo) odpre svoj kurzor in ga nato zapre; zapiranje povezave z bazo pa najverjetneje ni potrebno, saj lahko ves čas uporabljata isto povezavo (ko se pa program prekine, se tudi povezava prekine).

**Comment by DenisBencic** [comment]
Urejeno.
