### ISSUE TITLE
Nevarne poizvedbe

### ISSUE THREAD

**Issue by jaanos** [DenisBencic/Slovenske-fakultete-PB1-#3]
Vidim, da v svojem programu delata nevarne poizvedbe, npr.
https://github.com/DenisBencic/Slovenske-fakultete-PB1-/blob/a06c63d9867935c7a779b007ec27c81b0de4e738/iskalne_funkcije.py#L13
Z vstavljanjem podatkov s `format` namreč odpreta možnost za napade [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/). Namesto tega na mesto podatkov postavita vprašaje (brez navednic - za to bo poskrbel vmesnik), same podatke pa podajta v seznamu kot drugi argument metode `execute`, npr.
```python
    kurzor.execute("SELECT * FROM univerza WHERE naziv LIKE ?", ['%' + naziv + '%'])
``` 

Opažam tudi, da v `iskalne_funkcije.py` v vsaki funkciji odpreta novo povezavo na bazo in jo nato zapreta. Tega vama ni treba početi - dovolj bo, da povezavo odpreta enkrat (izven funkcij) in je ne zapirata, pač pa v vsaki funkciji odpreta in zapreta samo kurzor.

**Comment by DenisBencic** [comment]
Odpravljeno.
